### ISSUE TITLE
Graphical glitches in the hieroglyphs shown during loading

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_ios#82]
This seems to happen only for certain glyphs.
![2017-07-19 00 36 31](https://user-images.githubusercontent.com/3359222/28342810-5b7a4408-6c1a-11e7-836c-c99ff413f5b7.jpg)

In rare cases, the glyph may be missing entirely.

**Comment by ShezHsky** [comment]
Just to confirm, the weird streaking effect is due to the characters in the font containing these marks. The missing glyph is certainly an app bug.

<img width="912" alt="screen shot 2017-07-31 at 19 07 26" src="https://user-images.githubusercontent.com/12624320/28791209-9399c5b2-7623-11e7-98eb-50a8dc369d4d.png">

**Comment by ShezHsky** [comment]
This should be fixed in fcbf1aa0a36e43437c1adbed41870f5a0accc0c4, if not or we want to change the font just reopen this issue.
